<?php

namespace TSK\ScheduleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleEntityRepository extends EntityRepository
{
}
