imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    # - { resource: @MopaBootstrapSandboxBundle/Resources/config/themes.yml }
    # - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_menu.yml }
    # - { resource: @MopaBootstrapSandboxBundle/Resources/config/examples/example_navbar.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'TSKUserBundle:Form:fields.html.twig'
            - 'TSKPaymentBundle:Form:fields.html.twig'
            - 'TSKStudentBundle:Form:fields.html.twig'
            - 'TSKScheduleBundle:Form:fields.html.twig'
            - 'TSKRulerBundle:Form:field.html.twig'
            #- 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
            #- 'SamsonAutocompleteBundle:Form:autocomplete.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less: ~
            # node: /usr/local/bin/node
            # node_paths: [/usr/local/lib/node_modules]
            # apply_to: "\.less$"
        lessphp:
            apply_to: "\.less$"
            file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    # assets:
    #     img_bootstrap_glyphicons_black:
    #         inputs:
    #             -  "%kernel.root_dir%/../vendor/twbs/bootstrap/img/glyphicons-halflings.png"
    #         output: "img/glyphicons-halflings.png"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_menu:
    twig: true

# jms_security_extra:
    # expressions: true
    # voters:
        # disable_acl: true


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
        tsk_user.admin.block.erp_context_switcher:


sonata_admin:
    title:      TSK ERP System
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        # layout:  TSKUserBundle::sonata_layout.html.twig
        layout:  TSKUserBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    TSKUserBundle:CRUD:edit.html.twig

        # base_list_field: TSKUserBundle:CRUD:base_list_field.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: tsk_user.admin.block.erp_context_switcher }
    security:
        handler: tsk_user.security.tsk_acl_security_handler
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]



# sonata_doctrine_orm_admin:
#     templates:
#         form: 
#             - TSKProgramBundle:Admin:form_admin_fields.html.twig

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: TSK\UserBundle\Entity\User
    resetting:
        token_ttl: 10
    registration:
        form:
            type: tsk_user_registration
            validation_groups: [TSK]
            name: TSK_User_Registration_Form
    service:
        user_manager: tsk_user.user_manager.default

liip_theme:
    themes: ['bootstrap', 'initializr']
    active_theme: 'bootstrap'
    cookie:
        name: LiipThemeCookie
        lifetime: 31536000 # 1 year in seconds
        path: /
        domain: ~
        secure: false
        http_only: false

genemu_form:
    select2: ~
#     date: ~

fos_rest:
    routing_loader:
        default_format: xml 

jms_serializer:
    metadata:
        # auto_detection: true
        directories:
            TSKUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@TSKUserBundle/Resources/config/serializer/"


stof_doctrine_extensions:
    default_locale: en_US
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path: %kernel.root_dir%/../web/uploads
        
        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        
        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo 

    orm:
        default:
            timestampable: true
            blameable: true
            uploadable: true
            loggable: true


mopa_bootstrap:
    form:
        render_optional_text: false
    navbar: ~

