<?php

namespace TSK\StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentTokenRepository extends EntityRepository
{
}
