<?php
namespace TSK\StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingFamilyMembersRepository extends EntityRepository
{
    public function getAllForPrimaryStudent($primaryStudent)
    {
        $query = $this->_em->createQuery('SELECT u FROM TSK\StudentBundle\Entity\TrainingFamilyMembers u WHERE u.primaryStudent=:primaryStudent');
        $query->setParameter(':primaryStudent', $primaryStudent);
        try {
            $results = $query->getResult();
            return $results;
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * getNextSlotForPrimaryStudent 
     * Figures out the next open ordinal position in the
     * TrainingFamilyMember table for a primary student
     * 
     * @param mixed $primaryStudent 
     * @access public
     * @return void
     */
    public function getNextSlotForPrimaryStudent($primaryStudent)
    {
        $nextSlot = 1;
        $results = $this->getAllForPrimaryStudent($primaryStudent);
        if ($results) {
            foreach ($results as $result) {
                if ($result->getOrdinalPosition() == $nextSlot) {
                    $nextSlot++;
                }
            }
        }
        return $nextSlot;
    }
}
